// <auto-generated />
using System;
using System.Text.Json;
using CephAnalysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CephAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501225653_AddDiagnosisExtendedFields")]
    partial class AddDiagnosisExtendedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CephAnalysis.Domain.Entities.AnalysisSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("InferenceDurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("LandmarkMeta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OverlayImagesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("QueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ResultImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TotalDurationMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("TriggeredBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("XRayImageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredBy");

                    b.HasIndex("XRayImageId");

                    b.ToTable("AnalysisSessions");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnbRotationCorrected")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AnbUsed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("ApdiClassification")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("ClinicalNotes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("CorrectedAnb")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CrowdingSeverity")
                        .HasColumnType("text");

                    b.Property<string>("GrowthTendency")
                        .HasColumnType("text");

                    b.Property<string>("LowerIncisorInclination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MandibularPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxillaryPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OdiClassification")
                        .HasColumnType("text");

                    b.Property<string>("OdiNote")
                        .HasColumnType("text");

                    b.Property<string>("OverbiteClassification")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverbitesMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("OverjetClassification")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverjetMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SkeletalBorderline")
                        .HasColumnType("boolean");

                    b.Property<string>("SkeletalClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkeletalDifferential")
                        .HasColumnType("text");

                    b.Property<string>("SkeletalType")
                        .HasColumnType("text");

                    b.Property<string>("SoftTissueProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryText")
                        .HasColumnType("text");

                    b.Property<string>("UpperIncisorInclination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerticalPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("WarningsJson");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Landmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("ExpectedErrorMm")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsAiDetected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManuallyAdjusted")
                        .HasColumnType("boolean");

                    b.Property<string>("LandmarkCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LandmarkName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("XMm")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("XPx")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("YMm")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("YPx")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "LandmarkCode");

                    b.ToTable("Landmarks");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("Deviation")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("ExpectedError")
                        .HasColumnType("numeric");

                    b.Property<JsonDocument>("LandmarkRefs")
                        .HasColumnType("jsonb");

                    b.Property<string>("MeasurementCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MeasurementName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NormMean")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NormSD")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NormalMax")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("NormalMin")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "MeasurementCode");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MedicalRecordNo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MedicalRecordNo")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("GeneratedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludesLandmarkOverlay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesMeasurements")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesTreatmentPlan")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludesXray")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en");

                    b.Property<string>("ReportFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("SessionId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StudyDate")
                        .HasColumnType("date");

                    b.Property<string>("StudyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.TreatmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DiagnosisId")
                        .HasColumnType("uuid");

                    b.Property<short?>("EstimatedDurationMonths")
                        .HasColumnType("smallint");

                    b.Property<string>("EvidenceLevel")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceReference")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<short>("PlanIndex")
                        .HasColumnType("smallint");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<string>("RetentionRecommendation")
                        .HasColumnType("text");

                    b.Property<string>("Risks")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreatmentName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId", "PlanIndex");

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Doctor");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.XRayImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CalibrationKnownMm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<JsonDocument>("CalibrationPoint1")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("CalibrationPoint2")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("CalibrationRatio")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCalibrated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("PixelSpacingMm")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("XRayImages");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.AnalysisSession", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.User", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CephAnalysis.Domain.Entities.XRayImage", "XRayImage")
                        .WithMany("AnalysisSessions")
                        .HasForeignKey("XRayImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriggeredByUser");

                    b.Navigation("XRayImage");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.AnalysisSession", "Session")
                        .WithOne("Diagnosis")
                        .HasForeignKey("CephAnalysis.Domain.Entities.Diagnosis", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CephAnalysis.Domain.Entities.BoltonResult", "BoltonResult", b1 =>
                        {
                            b1.Property<Guid>("DiagnosisId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AnteriorFinding")
                                .HasColumnType("text");

                            b1.Property<decimal?>("AnteriorRatio")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)");

                            b1.Property<string>("OverallFinding")
                                .HasColumnType("text");

                            b1.Property<decimal?>("OverallRatio")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)");

                            b1.HasKey("DiagnosisId");

                            b1.ToTable("Diagnoses");

                            b1.WithOwner()
                                .HasForeignKey("DiagnosisId");
                        });

                    b.Navigation("BoltonResult")
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Landmark", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.AnalysisSession", "Session")
                        .WithMany("Landmarks")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.AnalysisSession", "Session")
                        .WithMany("Measurements")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Patient", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.User", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Report", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CephAnalysis.Domain.Entities.AnalysisSession", "Session")
                        .WithMany("Reports")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Study", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.User", "Doctor")
                        .WithMany("Studies")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CephAnalysis.Domain.Entities.Patient", "Patient")
                        .WithMany("Studies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.TreatmentPlan", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.Diagnosis", "Diagnosis")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.XRayImage", b =>
                {
                    b.HasOne("CephAnalysis.Domain.Entities.Study", "Study")
                        .WithMany("XRayImages")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.AnalysisSession", b =>
                {
                    b.Navigation("Diagnosis");

                    b.Navigation("Landmarks");

                    b.Navigation("Measurements");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Diagnosis", b =>
                {
                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Studies");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.Study", b =>
                {
                    b.Navigation("XRayImages");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.User", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("Studies");
                });

            modelBuilder.Entity("CephAnalysis.Domain.Entities.XRayImage", b =>
                {
                    b.Navigation("AnalysisSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
